service: election-guide-cors-proxy

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: prod
functions:
  proxy:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
